## Category (object)
+ id:SJlkcsaQ (required, string) - Unique Category identifier.
+ parent:S1_B6X97 (required, string) - The parent Category id. 'ROOT' is the root category.
+ title:Category 01 (required, string) - The Category title.
+ description:This is the Category 01 (required, string) - The Category description.
+ slug:cat01 (required, string) - The Category slug to use in paths. Parent+slug must be unique.
+ level:2 (required, number) - The Category level in the hierarchy.

## CategoryResponseOk (object)
+ ok:true (required, string) - Success indicator
+ category (required, Category) - A Category object

## CategoryResponseNoParent (object)
+ ok:false (required, string) - Failure indicator
+ error:parent_category_not_found (required, string) - Parent Category not found
+ data:xxxx (required, string) - The category id not found

## CategoryResponseDuplicateKey (object)
+ ok:false (required, string) - Failure indicator
+ error:duplicate_key (required, string) - Some unique key violation
+ data:E11000 duplicate key error index: micro.categories.$slug_1 dup key: { : "category01" } (required, string) - The database error  

## CategoryResponseValidationError (object)
+ ok:false (required, string) - Failure indicator
+ error:validation_error (required, string) - Some validation error
+ data:['title: Path `title` is required.'] (required, string) - The validation errors  

## CategoryRequest (object)
+ title:Category 01 (required, string) - The Category title.
+ description:This is the Category 01 (required, string) - The Category description.
+ slug:cat01 (required, string) - The Category slug to use in paths. Parent+slug must be unique.
+ parent:S1_B6X97 (required, string) - The parent Category id. 'ROOT' is the root category.

## Media (object)
+ id:100x100 (required, string) - The Media id
+ url:http://placehold.it/100x100 (required, string) - The Media url

## Product (object)
+ id:Hy79JiVV (required, string) - Unique Product identifier.
+ sku:0001 (required, string) - Product SKU.
+ status:ONLINE,DRAFT (required, enum[string]) - The status of the product from [ONLINE|DRAFT]. Default: 'DRAFT'.
+ title:Product 0001 (required, string) - The Product title.
+ description:This is the Product 0001 (required, string) - The Product description.
+ price:99.99 (required, number) - The Product price.
+ sale_price:79.99 (optional, number) - The Product sale price.
+ categories:SJlkcsaQ (optional, array[string]) - The Product categories.
+ medias (optional, array[Media]) - The Product medias.

## ProductList (array[Product])

## CreateProductRequest (Product)

## UpdateProductRequest (object)
+ status:ONLINE,DRAFT (required, enum[string]) - The status of the product from [ONLINE|DRAFT]. Default: 'DRAFT'.
+ title:Product 0001 (required, string) - The Product title.
+ description:This is the Product 0001 (required, string) - The Product description.
+ price:99.99 (required, number) - The Product price.
+ sale_price:79.99 (optional, number) - The Product sale price.
+ categories:SJlkcsaQ (optional, array[string]) - The Product categories.
+ medias (optional, array[Media]) - The Product medias.

## CategoryTree (array[CategoryTreeEntry])

## CategoryTreeEntry (object)
+ id:Hy79JiVV (required, string) - Unique Product identifier.
+ title:Product 0001 (required, string) - The Product title.
+ slug:cat01 (required, string) - The Category slug to use in paths.
