FORMAT: 1A
HOST: http://localhost:3000

# Catalog Service

Ecommerce Catalog service, part of the [microbase](http://microbase.io) 
ecosystem.

# Data Structures
<!-- include(dataStructures.apib) -->
# Group Catalog
<!-- include(operations.apib) -->
