sudo: required
language: node_js
node_js:
  - '6'
branches:
  only:
  - master
  - develop
services:
  - mongodb
  - docker
cache:
  directories:
  - $HOME/.yarn-cache
before_install:
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
install:
  - cd src
  - yarn --pure-lockfile
before_script:
  - sleep 15
script:
  - npm run test-cov-lcov
after_success:
  - cat ./lcov.info | ./node_modules/.bin/coveralls
  - cd ..
  - docker build -t $TRAVIS_REPO_SLUG:latest .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push $TRAVIS_REPO_SLUG:latest;
notifications:
  slack:
    secure: Efu7yHo8lMAhc+xaSRjwQ53uehAj7Mc5nHgATL4o/pHq8wUqXO89yhIksgWWg7iHjPdsTFxhmV5zf+jo5XKkOD7oRJTYBxS65G3YI93HBbs3Lyn2fFQlDK+Ggqs9rsTCmaAcbMn4KPN2p5/d9j+K1o/nBJPoNxMfdzdf9DeMuZ0Q8UGQPeXtiNaU2X7RyvjiC7m59tGWNiGZpb7QD9uZqwkyFjUAiM77eUIYm/pTSFh9dz1NbbE7CwijyhkoedaI4GmtxzazVXFivimB6xOhsKrCW3DKsFPPDdJshZ7zUW+HuzLN/2LcGbUTkIx6axAUXlPvMDdOWtSPb03KYSHCzHtLKyJCTPO/WkYwNqCiE9+tF6np9bBnASWK/0RAFJqRtioZhDq/Q22p/T/eYmUGhfjyeTPIvzum98EVXprKjvi1GIoFBX406HRmHxiE6OJrG4SNE377pZwXbumTBUZqwxpLHfzIIAak139DXT8sf9K9bphzmX+x26Mp9mHrY4B7IIH9zHZTKeMft25LuiNKGABXD+8qZ7tBfX6RQ6H9ptRCi2VuTqVbmuuqavW2s+MoVoa4jgm02Wi5V3yFqNXVMQiKgwDNnUH9Wd1kveX751JRMUz6ixJ4kjdwCkOGBdCbAf2zqsMPJydkJLEKNleAFolhljVLToc/N7DX7nPOpTY=
